CREATE TABLE product (
        product_id int GENERATED BY DEFAULT AS IDENTITY,
        product_no varchar(20) DEFAULT NULL,
        name varchar(100) DEFAULT NULL,
        category varchar(100) DEFAULT NULL,
        price double DEFAULT NULL,
        pur_price double DEFAULT NULL,
        storage int DEFAULT NULL,
        alarm_storage int DEFAULT NULL,
        PRIMARY KEY (product_id)
);
INSERT INTO product VALUES (1, '10001', 'Tea', 'Drinks', 3.5, 2.3, 20, 5);
INSERT INTO product VALUES (2, '10002', 'Juice', 'Drinks', 3.5, 2.3, 70, 5);
INSERT INTO product VALUES (3, '20001', 'Chocolate', 'Food', 4, 3.2, 108, 5);
INSERT INTO product VALUES (4, '10003', 'Coffee', 'Drinks', 5.5, 3.8, 21, 10);
INSERT INTO product VALUES (5, '40001', 'Marlboro', 'Cigarette', 10.5, 7.4, 239, 10);
INSERT INTO product VALUES (6, '30001', 'Red Wine', 'Wine', 35, 24.8, 10, 5);
INSERT INTO product VALUES (7, '10004', 'Cola', 'Drinks', 3, 1.8, 38, 10);
INSERT INTO product VALUES (8, '30002', 'White wine', 'Wine', 30, 20, 50, 5);
INSERT INTO product VALUES (9, '50001', 'Crisps', 'Snacks', 7, 5, 100, 5);
INSERT INTO product VALUES (10, '60001', 'Toilet paper', 'Household', 5, 4, 150, 5);
INSERT INTO product VALUES (11, '50002', 'Potato chips', 'Snacks', 2, 1.7, 200, 5);
INSERT INTO product VALUES (12, '60002', 'Mop', 'Household', 10, 9, 150, 5);
INSERT INTO product VALUES (13, '40002', 'Winston', 'Cigarette', 20, 15, 40, 5);
CREATE TABLE purchase (
        purchase_id int GENERATED BY DEFAULT AS IDENTITY,
        purchase_category varchar(20) DEFAULT NULL,
        purchase_name varchar(100) DEFAULT NULL,
        purchase_quantity int DEFAULT NULL
);
INSERT INTO purchase VALUES (1, 'Drinks', 'Tea', 50);
INSERT INTO purchase VALUES (2, 'Drinks', 'Juice', 60);
INSERT INTO purchase VALUES (3, 'Food', 'Chocolate', 70);
INSERT INTO purchase VALUES (4, 'Drinks', 'Coffee', 20);
INSERT INTO purchase VALUES (5, 'Cigarette', 'Marlboro', 45);
INSERT INTO purchase VALUES (6, 'Wine', 'Red Wine', 50);
INSERT INTO purchase VALUES (7, 'Drinks', 'Cola', 10);
INSERT INTO purchase VALUES (8, 'Wine', 'White wine', 5);
INSERT INTO purchase VALUES (9, 'Snacks', 'Crisps', 35);
INSERT INTO purchase VALUES (10, 'Household', 'Toilet paper', 10);